version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=app_admin
      - POSTGRES_PASSWORD=app_password
      - POSTGRES_DB=millan_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: